### ISSUE TITLE
nextflow DSL1 is not supported by current version of nextflow any more

### ISSUE THREAD

**Issue by dmonizer** [taltechnlp/est-asr-pipeline#1]
got the error when running:
Nextflow DSL1 is no longer supported — Update your script to DSL2, or use Nextflow 22.10.x or earlier

**Comment by aivo0** [comment]
Nextflow has very slowly introduced a new syntax. In gives no tangible benefits for us so we have not adopted it. Please reinstall an earlier version of Nextflow and try again. I will update the readme that Nextflow 22.10.x or earlier has to be used at the moment.

**Comment by aivo0** [comment]
Actually you should also be able to not reinstall and just give Nextflow the target version to run like this:
NXF_VER=22.10.0 nextflow run transcribe.nf

**Comment by dmonizer** [comment]
Great, will try. Aitäh ;)

**Comment by aivo0** [comment]
Also, seems OpenJDK 20 cannot be used with this lower Nextflow version. Works with OpenJDK version 18.
