### ISSUE TITLE
Recent Dockerfile changes require building the image, package repository hasn't been updated

### ISSUE THREAD

**Issue by Vapper** [taltechnlp/est-asr-pipeline#2]
Currently running the system with the latest code and pulling the image from Docker Hub will lead to errors when trying to call 'silero_vad' model in 'bin/find_speech_segments.py'. README.md should either require building the docker image on your own or the package repository should get an update.

**Comment by aivo0** [comment]
Correct, please currently use the version from 2 commits ago (https://github.com/taltechnlp/est-asr-pipeline/tree/41bae3208db5b3b96f862042f7fdca625f9abd55). The latest commits were untested and never intended to be left as-is for long. A new Docker image must be built, tested and uploaded to Docker Hub for this version to work.
